# Generated by Django 3.2.3 on 2021-06-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVirtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=20)),
                ('precioKiloMayorista', models.IntegerField(null='true')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Productor',
            new_name='Agricultor',
        ),
    ]
