# Generated by Django 3.2.3 on 2021-06-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVirtual', '0003_auto_20210608_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultor',
            name='apmaterno',
            field=models.CharField(max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='email',
            field=models.EmailField(max_length=254, null='true', verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='Rut (sin puntos y con guión)'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='telefono1',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
    ]
