# Generated by Django 3.2.3 on 2021-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVirtual', '0005_auto_20210608_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='bancoAsociado',
            field=models.CharField(blank=True, max_length=20, null='true', verbose_name='Banco Asociado'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='nroCuenta',
            field=models.IntegerField(blank=True, null='true', verbose_name='Nro Cuenta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apmaterno',
            field=models.CharField(max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='appaterno',
            field=models.CharField(max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='Rut (sin puntos, con guion)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono1',
            field=models.CharField(max_length=15, verbose_name='Telefono 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(max_length=15, null='true', verbose_name='Telefono 2'),
        ),
    ]
