# Generated by Django 3.2.3 on 2021-06-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVirtual', '0008_alter_cliente_telefono2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioKiloMayorista',
            field=models.IntegerField(blank=True, null='true'),
        ),
    ]
