# Generated by Django 3.2.3 on 2021-06-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVirtual', '0009_alter_producto_preciokilomayorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agricultor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaVirtual.agricultor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank='True', null=True, upload_to='productos'),
        ),
    ]
