# Generated by Django 3.2.3 on 2021-06-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaVirtual', '0010_auto_20210623_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='agricultor',
        ),
    ]
